# Generated by Django 4.0.5 on 2022-06-26 17:30

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_Album', models.CharField(max_length=50)),
                ('cover_path', models.ImageField(upload_to='Imagens/Capas_Albuns')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['title_Album'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_Music', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('music_path', models.FileField(upload_to='Music/%y')),
                ('music_image', models.ImageField(upload_to='Imagens/Capas_Musicas')),
                ('length', models.PositiveIntegerField(default=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album_Tracks', to='backend.album')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('TypeUser', models.CharField(choices=[('NORMAL', 'Normal'), ('EDITOR', 'Editor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.FileField(upload_to='Videos/%y')),
                ('length', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50, null=True)),
                ('urlStreaming', embed_video.fields.EmbedVideoField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='shareGroup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('music', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('video', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.video')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sharegroup')),
                ('UserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Critics',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.CharField(choices=[('Pessimo', '0'), ('Mau', '1'), ('Agradavel', '2'), ('Bom', '3'), ('Muito Bom', '4'), ('Excelente', '5')], max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album_critic', to='backend.album')),
            ],
            options={
                'ordering': ['-album'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo_path', models.ImageField(upload_to='Imagens/Artistas')),
                ('description', models.CharField(max_length=50, null=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.music')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_albuns', to='backend.user'),
        ),
    ]
